//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.19 at 05:31:18 PM EET 
//


package savechat;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the savechat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SavedChat_QNAME = new QName("", "SavedChat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: savechat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SavedChatType }
     * 
     */
    public SavedChatType createSavedChatType() {
        return new SavedChatType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SavedChatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SavedChat")
    public JAXBElement<SavedChatType> createSavedChat(SavedChatType value) {
        return new JAXBElement<SavedChatType>(_SavedChat_QNAME, SavedChatType.class, null, value);
    }

}
